spring:
  security:
    oauth2:
      client:
        registration:
          example:
            client-id: "spring"
            client-secret: "secret"
            client-name: "Example Security"
            provider: "spring"
            scope: "openid, profile"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          spring:
            issuer-uri: "http://localhost:9090"
logging:
  level:
    root: debug